apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-pdbwatcher
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx:latest

