apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pdbwatchers.apps.mydomain.com
spec:
  group: apps.mydomain.com
  names:
    kind: PDBWatcher
    listKind: PDBWatcherList
    plural: pdbwatchers
    singular: pdbwatcher
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                pdbName:
                  type: string
                  description: "The name of the Pod Disruption Budget to watch."
                deploymentName:
                  type: string
                  description: "The name of the Deployment to scale."
              required:
                - pdbName
                - deploymentName
            status:
              type: object
              properties:
                currentReplicas:
                  type: integer
                  description: "The current number of replicas of the Deployment."
                disruptionsAllowed:
                  type: integer
                  description: "The current number of disruptions allowed for the PDB."
                evictionLogs:
                  type: array
                  items:
                    type: object
                    properties:
                      podName:
                        type: string
                      evictionTime:
                        type: string
                      status:
                        type: string
                scaleFactor:
                  type: integer
                  description: "The number by which to scale the Deployment."
                  minimum: 1
                minReplicas:
                  type: integer
                  description: "The minimum number of replicas to maintain."
                  minimum: 1
                maxReplicas:
                  type: integer
                  description: "The maximum number of replicas to maintain."
                  minimum: 1
              required:
                - currentReplicas
                - disruptionsAllowed
                - scaleFactor
                - minReplicas
                - maxReplicas
      additionalPrinterColumns:
        - name: PDB Name
          type: string
          description: "The name of the Pod Disruption Budget"
          jsonPath: .spec.pdbName
        - name: Deployment Name
          type: string
          description: "The name of the Deployment"
          jsonPath: .spec.deploymentName
        - name: Scale Factor
          type: integer
          description: "The scale factor for the Deployment"
          jsonPath: .status.scaleFactor
        - name: Min Replicas
          type: integer
          description: "The minimum number of replicas"
          jsonPath: .status.minReplicas
        - name: Max Replicas
          type: integer
          description: "The maximum number of replicas"
          jsonPath: .status.maxReplicas
        - name: Current Replicas
          type: integer
          description: "The current number of replicas"
          jsonPath: .status.currentReplicas
        - name: Allowed Disruptions
          type: integer
          description: "The allowed number of disruptions"
          jsonPath: .status.disruptionsAllowed
