apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pdbwatcher-role
  namespace: default
rules:
- apiGroups: ["apps.mydomain.com"]
  resources: ["pdbwatchers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pdbwatcher-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pdbwatcher-role
  apiGroup: rbac.authorization.k8s.io

