apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-manager-role
  namespace: default
rules:
  # Allow access to Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
  # Allow read access to Pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  # Allow read and update access to Deployments and StatefulSets
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
  # Allow read access to PodDisruptionBudgets
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch"]
