apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-manager-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: default
roleRef:
  kind: Role
  name: controller-manager-role
  apiGroup: rbac.authorization.k8s.io
