apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-rolebinding
subjects:
- kind: ServiceAccount
  name: eviction-webhook
  namespace: default
roleRef:
  kind: ClusterRole
  name: webhook-role
  apiGroup: rbac.authorization.k8s.io
