apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: paulgmiller/k8s-pdb-autoscaler
  newName: docker.io/paulgmiller/eviction-autoscaler
  newTag: 0.1.0-dalec
