package controllers

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	policyv1 "k8s.io/api/policy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

var _ = Describe("maxUnavailable PDB adoption helpers", func() {
	DescribeTable("normalizes a relative policy",
		func(maxUnavailable intstr.IntOrString, replicas, expected int32, annotation string) {
			pdb := &policyv1.PodDisruptionBudget{
				Spec: policyv1.PodDisruptionBudgetSpec{MaxUnavailable: &maxUnavailable},
			}

			changed, err := normalizeMaxUnavailable(pdb, replicas)
			Expect(err).NotTo(HaveOccurred())
			Expect(changed).To(BeTrue())
			Expect(pdb.Spec.MaxUnavailable).To(BeNil())
			Expect(pdb.Spec.MinAvailable).To(Equal(&intstr.IntOrString{Type: intstr.Int, IntVal: expected}))
			Expect(pdb.Annotations).To(HaveKeyWithValue(OriginalMaxUnavailableAnnotationKey, annotation))
		},
		Entry("integer", intstr.FromInt32(1), int32(5), int32(4), "1"),
		Entry("percentage with Kubernetes rounding", intstr.FromString("25%"), int32(5), int32(3), `"25%"`),
		Entry("allowance larger than replicas", intstr.FromInt32(10), int32(3), int32(0), "10"),
	)

	It("leaves a minAvailable-only PDB unchanged", func() {
		minAvailable := intstr.FromInt32(2)
		pdb := &policyv1.PodDisruptionBudget{Spec: policyv1.PodDisruptionBudgetSpec{MinAvailable: &minAvailable}}
		before := pdb.DeepCopy()

		changed, err := normalizeMaxUnavailable(pdb, 5)
		Expect(err).NotTo(HaveOccurred())
		Expect(changed).To(BeFalse())
		Expect(pdb).To(Equal(before))
	})

	It("does not partially mutate a PDB with an invalid preserved value", func() {
		minAvailable := intstr.FromInt32(2)
		pdb := &policyv1.PodDisruptionBudget{
			ObjectMeta: metav1.ObjectMeta{Annotations: map[string]string{
				OriginalMaxUnavailableAnnotationKey: `"not-a-percentage"`,
			}},
			Spec: policyv1.PodDisruptionBudgetSpec{MinAvailable: &minAvailable},
		}
		before := pdb.DeepCopy()

		changed, err := normalizeMaxUnavailable(pdb, 5)
		Expect(err).To(HaveOccurred())
		Expect(changed).To(BeFalse())
		Expect(pdb).To(Equal(before))
	})

	It("rejects a null preserved value", func() {
		pdb := &policyv1.PodDisruptionBudget{ObjectMeta: metav1.ObjectMeta{Annotations: map[string]string{
			OriginalMaxUnavailableAnnotationKey: "null",
		}}}
		_, _, err := originalMaxUnavailable(pdb)
		Expect(err).To(HaveOccurred())
	})

	It("keeps autogenerated PDB behavior when no allowance is preserved", func() {
		pdb := &policyv1.PodDisruptionBudget{}
		minAvailable, err := managedMinAvailable(pdb, 7)
		Expect(err).NotTo(HaveOccurred())
		Expect(minAvailable).To(Equal(int32(7)))
	})
})
