apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pdbwatchers.apps.mydomain.com
spec:
  group: apps.mydomain.com
  names:
    kind: PDBWatcher
    listKind: PDBWatcherList
    plural: pdbwatchers
    singular: pdbwatcher
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                  description: "The name of the Deployment to scale."
                pdbName:
                  type: string
                  description: "The name of the Pod Disruption Budget to watch."
              required:
                - pdbName
            status:
              type: object
              properties:
                evictionLogs:
                  type: array
                  items:
                    type: object
                    properties:
                      podName:
                        type: string
                      evictionTime:
                        type: string
                        format: date-time
                      status:
                        type: string
                minReplicas:
                  type: integer
                  description: "The minimum number of replicas to maintain."
                  minimum: 1
                resourceVersion:
                  type: string
                  description: "Resource version of the deployment."
              required:
                - minReplicas
                - resourceVersion
      additionalPrinterColumns:
        - name: PDB Name
          type: string
          description: "The name of the Pod Disruption Budget"
          jsonPath: .spec.pdbName
        - name: Deployment Name
          type: string
          description: "The name of the Deployment"
          jsonPath: .spec.deploymentName
        - name: Min Replicas
          type: integer
          description: "The minimum number of replicas"
          jsonPath: .status.minReplicas
      subresources:
        status: {}
