---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eviction-autoscaler.fullname" . }}-manager-role
  labels:
    app.kubernetes.io/name: eviction-autoscaler
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "eviction-autoscaler.chart" . }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - update
- apiGroups:
  - eviction-autoscaler.azure.com
  resources:
  - evictionautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eviction-autoscaler.azure.com
  resources:
  - evictionautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - eviction-autoscaler.azure.com
  resources:
  - evictionautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eviction-autoscaler.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/name: eviction-autoscaler
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "eviction-autoscaler.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eviction-autoscaler.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "eviction-autoscaler.fullname" . }}-controller-manager
  namespace: {{ .Values.namespace }}
