apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eviction-autoscaler.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eviction-autoscaler
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "eviction-autoscaler.chart" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eviction-autoscaler.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eviction-autoscaler
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "eviction-autoscaler.chart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eviction-autoscaler.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "eviction-autoscaler.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
