{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eviction-autoscaler.fullname" . }}-metrics-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "eviction-autoscaler.name" . }}
    app.kubernetes.io/component: metrics
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "eviction-autoscaler.chart" . }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - name: {{ .Values.metrics.service.portName }}
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: {{ .Values.ports.metrics }}
  selector:
    app.kubernetes.io/name: {{ include "eviction-autoscaler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
