apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eviction-autoscaler.fullname" . }}-controller-manager-pdb
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: eviction-autoscaler
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "eviction-autoscaler.chart" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eviction-autoscaler
      app.kubernetes.io/instance: {{ .Release.Name }}
