apiVersion: apps/v1
kind: Deployment
metadata:
  name: eviction-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eviction-webhook
  template:
    metadata:
      labels:
        app: eviction-webhook
    spec:
      serviceAccountName: eviction-webhook
      containers:
        - name: eviction-webhook
          image: javgarcia0907/iamgreat:v6
          ports:
            - containerPort: 9443
          volumeMounts:
            - name: webhook-certs
              mountPath: /ect/webhook/certs # Ensure this path matches your server configuration
              readOnly: true
          env:
            - name: TLS_CERT_FILE
              value:  /etc/webhook/certs/tls.crt  
            - name: TLS_KEY_FILE
              value: /etc/webhook/certs/tls.key
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: eviction-webhook-service
  namespace: default
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: eviction-webhook