apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: eviction-webhook
webhooks:
  - name: eviction.mydomain.com
    clientConfig:
      service:
        name: eviction-webhook-service
        namespace: default
        path: /validate-eviction
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lVWWc0b0llay9WQUZxREEzTWNIZ3pRemhDb1Jzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0lUWGxTYjI5MFEwRXdIaGNOTWpRd09EQTNNVGt5TWpFMldoY05NelF3T0RBMQpNVGt5TWpFMldqQVRNUkV3RHdZRFZRUUREQWhOZVZKdmIzUkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTEo5VWxCVld6LzA0Z0orZlYwWGoxd2pQQkZEK2JtNzZvQVEyM1l3eVA4NlZ0VDgKdXpQZ1FvU0ZsVGJ2MlJQRTQ0eEkxWWNLZXZKSWNDcnUvdFYvSGIrNTVHSDE2b3BZcnEybkNtNDFpdHNGaVVFMApDdW5WWCtKdjBTaDUyYTl1eU1DaGtxT3RmejdEU3d3bFFITUZHYjgxMDlLZkFwZWVnV0dpR0ZzMUpiUjMwUythCm44cjRsUmtGWTQ5RXVCcXdIcEpoeUl2akx6dDA5aWRnRHVhRlNpQUQxclBBd2dMWEhHYllWOWVrUkpWVld3QnMKS1BpTVVNUzVYaGFpVkQzZ3NSZjJqeUhWQXovcVlvbGdXMUFwd3NVWlJjaUZOTXFYajEvYUNTYSs2czdyRFJtNgpleUt0ZU1jSE1hKytWcUxpU0t4VG43V0tyMzAzL0FMeExkYUhGUUVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFCkZPVzh1dGNSSEZmUzU3QWJTSUtUN2tocjBsYmVNQjhHQTFVZEl3UVlNQmFBRk9XOHV0Y1JIRmZTNTdBYlNJS1QKN2tocjBsYmVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRmJBeG5VYQp1YXo2eERuenRQbjY2aHlUOHNsTHlnMG40bzBaYjh3MUdEMVdHK0x2d1dlVy95L1FsU3paZ1JIUkJBanA0SnY3Cmd5MDZHTjFFNlNPd1JoZTQ5bGdyM0FWSUVWR1pXREF3NVlGS0pTS1V2TVpHQytOWWt4TDRVdU9CbTRNVjlyWW8KaElxemdmaVRBRXVYQmhuMUlTaWlJQjZUUG9NdW8xUFVZOVBUOVM0VStQT0wyRmVYQ1pJc0tnd01BQk9LbU9hNgpEaThQRDJXMEo2anR4QTV0TVFmNThibTBIRnRVb0RCK0wxMnhqZm9teTJSQ25vMlBXdU1sWURHQ0VVNExYQnhKCmg4UzFKREhvZHNvVUdvYTlBRVJ4WjlQYTFyUW9ZSU14QStSR2ppYzhIaFU3dCtWbEVWVWRiakl2VFdQV3poTnMKUkorbUxaSDVqSCsrUlhNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods/eviction"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail