apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: eviction-webhook
webhooks:
  - name: eviction.mydomain.com
    clientConfig:
      service:
        name: eviction-webhook-service
        namespace: default
        path: /validate-eviction
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVVHlYL0NjbXZzaVg5ZWFMVFRIb2tQM2hhaUEwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01MbVJsWm1GMWJIUXVjM1pqTUI0WERUSTBNRGd3TVRJek1EQXpORm9YRFRJMQpNRGd3TVRJek1EQXpORm93RnpFVk1CTUdBMVVFQXd3TUxtUmxabUYxYkhRdWMzWmpNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFrQW5zQlNWQ0FmL0JPYXE2ZlJ3RjFlSmpJVDJOWHdCWUFOVEIKTy9zQjY0bVVPN25jZG9laUNSUW1GclBVTXZzUjhPV3FHT0oybzJkTSsxdkJ1R2lwNTEwQXEzZHdUTGlKZHpubQpIMjhrOHFicjJvK3RoK1BLZCttblRjQ2pDeDJaVmtSOVJ4K2gyNGVqMjZyMHVFOHhmaTJ3Q1h1S2d4Z0w5OFdxCmJlT0lHZzhURXVtbjBOcC9VekdERE1BM1ZQSXpLRDd6anI5TVpxYXpvRTVaMVhCRVRjUjU5dkhRbHNOeGpMdHoKUG1wbnkyb2wzTWdkWUpwNkVJZzljcDlpenZJcXZkYVFVaWhSWlRxRlVNeE4wR2pPZlkzOXhQMkorMEtsOTlkbgpkTUR3eEIvd0xqS29leW0vNnM2Ymx3b2NQUTJUTllPbEQvVWkwSC9BcjFWRit0VWZXUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVWp3bitYN2hzMTNvNUcxeUtFWW1KU1N1SEFqa3dId1lEVlIwakJCZ3dGb0FVanduK1g3aHMKMTNvNUcxeUtFWW1KU1N1SEFqa3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBQnZxL3NwNXAxWUcvNFhFL05GTW9WckxES1Q4ZjMxcldRZS9YNDJBVERERVBicEsrN0VKbExNdVY0L25JCnFqd1BheUx3bFE5ODNOejdHcWxuL1IyYlVjRVNZUWJsQVdzcURydkZBaVVRZnA2TGxIYjVVWktGOGNoR05VdWgKYWRtYTZhQ0t4VTBUWkN4eVk1V1hkd1gySzVzTEtNS2tRU0RsK3FONTYyOSs0M3dLazlUN3dwdzNlZ0pCcGNVNApyTHh6c3MrNjcwUG5BTkw0WXJQajdhNWJ1NHBVNmlGNVI1TW5kWGdjYXg5OU5nQldQSDJpQWdCWDhNeUlrd0NaCnpUQVU0K3piSHl3Z0FpSlp3dTVtS05PSWE1UEY4RzZYbWt0WDN2dS9uOCthZ1lOazM4QmVuY2MxRndkbkF5YUcKcnVLMFRuTE5BazhNV01XU0hoN2g5TmZ3NkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==  
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods/eviction"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
